name: Docker Image CI Manual Job

on:
  workflow_dispatch:
    inputs:
      tag:
        description: |
          RPFM git branch or tag
        required: true
        default: 'master'
      profile:
        description: |
          Cargo build profile.
          Enter "release" for an optimized profile.
          Leave "debug" for an unoptimized profile.
        required: true
        default: 'debug'
      upstream:
        description: |
          RPFM upstream repo.
          Default: https://github.com/Frodo45127/rpfm.git
        required: false
        default: 'https://github.com/Frodo45127/rpfm.git'
          

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "${{ github.repository }}"
  UPSTREAM: "Frodo45127/rpfm"

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
        
    - name: Checkout upstream repository
      uses: actions/checkout@v2
      with:
        repository: ${{ env.UPSTREAM }}
        ref: ${{ github.event.inputs.tag }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0
      id: buildx
      with:
        install: true
        driver: docker-container
        driver-opts: |
          image=moby/buildkit:master
          network=host
          
    - name: Get info
      id: repo
      run: |
        echo "::set-output name=name::$(echo ${GITHUB_REPOSITORY#*/})"
        echo "::set-output name=sha::$(git rev-parse --verify ${{ github.event.inputs.tag }})"
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3.6.0
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo.outputs.name }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}},priority=900,value=${{ github.event.inputs.tag }}
          type=edge,priority=700,branch=${{ github.event.inputs.tag }}
          type=match,pattern=master,group=0,value=${{ github.event.inputs.tag }}
          type=raw,value=${{ steps.repo.outputs.sha }}
    
    - name: Checkout local repository
      uses: actions/checkout@v2
      with:
        path: docker
    
    - name: Log in to the Container registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2.6.1
      with:
        context: docker
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          VERSION=${{ github.event.inputs.tag }}
          PROFILE=${{ github.event.inputs.profile }}
          UPSTREAM=${{ github.event.inputs.upstream }}
